# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 12:48
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('aname', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[catalog.models.validate_asset_name])),
                ('atype', models.CharField(choices=[('S', 'satellite'), ('A', 'antenna')], default='S', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('acclass', models.CharField(choices=[('do', 'dove'), ('r', 'rapideye'), ('di', 'dish'), ('y', 'yagi')], default='do', max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='aclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aclass', to='catalog.AssetClass'),
        ),
    ]
